FROM oven/bun:1 AS base

# set workdir at repo root
WORKDIR /apps
ARG DATABASE_URL
COPY packages ./packages
COPY bun.lock ./bun.lock

COPY  package.json ./package.json
COPY  turbo.json ./turbo.json

COPY apps/web /apps/frontend

RUN bun install

RUN bun run db:generate

WORKDIR /apps/frontend

EXPOSE 3000

RUN DATABASE_URL=${DATABASE_URL} bun run build
CMD [ "bun" ,"run" , "start" ]

