FROM oven/bun:1 AS base

# set workdir at repo root
WORKDIR /apps

COPY packages ./packages
COPY bun.lock ./bun.lock

COPY package.json ./package.json
COPY turbo.json ./turbo.json

COPY apps/backend /apps/backend

RUN bun install

RUN bun db:generate

WORKDIR /apps/backend
EXPOSE 8080

CMD [ "bun" ,"run" , "index.ts" ]

