FROM oven/bun:1 AS base

WORKDIR /home

COPY package.json bun.lock turbo.json ./
COPY packages ./packages
COPY apps/backend ./apps/backend

RUN bun install

# Run prisma generate from root
RUN bun db:generate

WORKDIR /home/apps/backend
EXPOSE 5000
CMD ["bun", "run", "index.ts"]
